controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  qm_controller:
    type: qm/QMController
  qm_controller_arm:
    type: qm/QMMpcController